### ISSUE TITLE
Email+ - Date formatting helpers

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-app-htmlemail#34]
Emails generated with EmailPlus need some control over how dates are rendered. A helper like:

```
{{local_date SomeDate "yyyy"}}
```

or:

```
{{utc_date SomeDate "o"}}
```

would help to produce more readable date output.

**Comment by SimonCropp** [comment]
wouldnt it be simple to have a extra props for TimestampUtc and LocalTimestamp that are unambiguous ? that would suffice for our requirements

**Comment by nblumhardt** [comment]
That's already done, see: https://github.com/datalust/seq-apps/blob/master/src/Seq.App.EmailPlus/EmailReactor.cs#L151

(I can see how the description above is confusing, hopefully your comment and my reply now clarify it :-))

**Comment by SimonCropp** [comment]
@nblumhardt but that uses the default tostring. which is not unambiguous

**Comment by nblumhardt** [comment]
Ah, I see what you mean - `{{format_date $UtcTimestamp "o"}}` etc. ... The challenge is handling dates that are included in other event properties, for example an event might have a `CreatedDate` property which, irrespective of whether it's expressed as a local or UTC timestamp, the user might prefer to show as one or the other. Splitting formatting from time zone conversions would be another reasonable approach, though - I'm not sure how much support Handlebars.NET has for nested function application, but in principle that does seem cleaner 👍

**Comment by nblumhardt** [comment]
#74 adds support for this 🎉
