### ISSUE TITLE
How to use handlebarsjs custom helpers with from template in Seq and Seq.App.EmailPlus

### ISSUE THREAD

**Issue by andreimyvc** [datalust/seq-app-htmlemail#90]
How to use handlebarsjs custom helpers with from template in Seq and Seq.App.EmailPlus? I get the following error when I try to use a handlebarsjs custom helper: HandlebarsDotNet.HandlebarsRuntimeException: Template references a helper that cannot be resolved. Helper 'formatDate'

```
<html>
<head>        
    <script type="text/javascript">
alert(Handlebars);
        Handlebars.registerHelper('formatDate', function(date) {
            return new Date(date).toLocaleDateString() + ' ' + new Date(date).toLocaleTimeString();
        });
    </script>
</head>
<body>    
    <divstyle="display: none;" id="entry-template">{{formatDate "2019-01-01"}}</div>  
    <div id="placeholder"></div>        
</body>
</html>
```

**Comment by nblumhardt** [comment]
Thanks for the suggestion, @MattMofDoom 👍

**Comment by nblumhardt** [comment]
#74 adds support for custom time zone selection and date formatting.
